#+TITLE: Knowledge Management
#+AUTHOR: Kyeong Soo Choi
#+STARTUP: overview
#+OPTIONS: toc:2 num:3
#+PROPERTY: header-args:emacs-lisp :mkdirp yes :results none

Configuration for Org-mode and knowledge management tools including org-roam, org-gcal, and related packages.

* Org Mode Core Configuration

Core Org-mode settings including babel languages, templates, and basic customization.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  ;;; org-conf.el --- Org-mode and knowledge management configuration  -*- lexical-binding: t; -*-
  ;;; Commentary:
  ;;; Code:

  ;; Configure browser for opening URLs (fixes LaTeXiT issue on macOS)
  (setq browse-url-browser-function 'browse-url-default-macosx-browser)

  ;; Required packages for org extensions
  (use-package org-contrib)
  (use-package ob-typescript)
  (use-package ob-powershell)
  (use-package ob-http)
  (use-package ob-restclient)

  (use-package org
    :pin org
    :commands (org-capture org-agenda)
    :custom
    ;; Agenda and logging
    (org-agenda-start-with-log-mode t)
    (org-log-done 'time)
    (org-log-into-drawer t)

    ;; Editing behavior
    (org-catch-invisible-edits 'show)
    (org-edit-timestamp-down-means-later t)
    (org-fast-tag-selection-single-key 'expert)
    (org-src-window-setup 'current-window)

    ;; Export settings
    (org-export-coding-system 'utf-8)
    (org-export-kill-product-buffer-when-displayed t)
    (org-html-validation-link nil)

    ;; LaTeX export
    (org-latex-compiler "xelatex")
    (org-latex-pdf-process '("latexmk -xelatex -synctex=1 -f -interaction=nonstopmode -output-directory=%o %f"))

    ;; Display and appearance
    (org-hide-emphasis-markers t)
    (org-pretty-entities nil)
    (org-startup-indented nil)
    (org-startup-with-inline-images t)
    (org-display-remote-inline-images 'download)
    (org-image-actual-width '(450))
    (org-tags-column 80)

    :config
    ;; Load org-tempo for easy template expansion
    (require 'org-tempo)

    ;; Load babel language support
    (require 'ob-js)
    (require 'ob-typescript)
    (require 'ob-ruby)

    ;; Add custom structure templates
    (add-to-list 'org-structure-template-alist '("txt"  . "src text"))
    (add-to-list 'org-structure-template-alist '("cc"   . "src C"))
    (add-to-list 'org-structure-template-alist '("sh"   . "src shell"))
    (add-to-list 'org-structure-template-alist '("zsh"  . "src zsh"))
    (add-to-list 'org-structure-template-alist '("bash" . "src bash"))
    (add-to-list 'org-structure-template-alist '("posh" . "src powershell"))
    (add-to-list 'org-structure-template-alist '("el"   . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("py"   . "src python"))
    (add-to-list 'org-structure-template-alist '("js"   . "src js"))
    (add-to-list 'org-structure-template-alist '("ts"   . "src typescript"))
    (add-to-list 'org-structure-template-alist '("java" . "src java"))
    (add-to-list 'org-structure-template-alist '("scm"  . "src scheme"))
    (add-to-list 'org-structure-template-alist '("sql"  . "src sql"))
    (add-to-list 'org-structure-template-alist '("rust" . "src rust"))
    (add-to-list 'org-structure-template-alist '("rb"   . "src ruby"))

    ;; Enable babel languages - only load those that are available
    (org-babel-do-load-languages
     'org-babel-load-languages
     (seq-filter
      (lambda (pair)
        (locate-library (concat "ob-" (symbol-name (car pair)))))
      '((dot        . t)
        (C          . t)
        (gnuplot    . t)
        (latex      . t)
        (python     . t)
        (js         . t)
        (typescript . t)
        (shell      . t)
        (zsh        . t)
        (bash       . t)
        (posh       . t)
        (powershell . t)
        (scheme     . t)
        (sql        . t)
        (sqlite     . t)
        (ruby       . t)
        (emacs-lisp . t)
        (http       . t)
        (restclient . t))))

    ;; Fix electric-pair-mode for org-mode angle brackets
    (defun handle-electric-pair-inhibit (c)
      (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c)))

    (defun handle-org-mode-hook()
      (setq-local electric-pair-inhibit-predicate #'handle-electric-pair-inhibit))

    (add-hook 'org-mode-hook #'handle-org-mode-hook)

    ;; Load org-remoteimg for remote image display
    (add-to-list 'load-path (expand-file-name "elisp/settings" user-emacs-directory))
    (require 'org-remoteimg))
#+end_src

* Org Download

Drag-and-drop images and screenshots into org buffers.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-download
    :after org
    :custom
    ;; Store images in a local "images" directory
    (org-download-image-dir "images")

    ;; Don't create heading-based subdirectories
    (org-download-heading-lvl nil)

    ;; Screenshot method based on OS
    (org-download-screenshot-method
     (cond ((eq system-type 'darwin) "screencapture -i %s")
           ((eq system-type 'gnu/linux) "scrot -s %s")))

    :config
    ;; Enable inline display of remote images
    (setq org-download-display-inline-images 'posframe))
#+end_src

* Org Appear (Disabled)

Shows hidden emphasis markers and links when cursor is on them. Currently disabled.

#+begin_src emacs-lisp :tangle no
  (use-package org-appear
    :hook
    (org-mode . org-appear-mode)
    :custom
    (org-appear-autoemphasis t)
    (org-appear-autolinks t)
    (org-appear-autosubmarkers t)
    (org-appear-autoentities t)
    (org-appear-autokeywords t)
    (org-appear-inside-latex t)
    (org-appear-delay 0.0)
    (org-appear-trigger 'always))
#+end_src

* Org Google Calendar

Bidirectional sync between Org-mode and Google Calendar.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-gcal
    :after org
    :custom
    ;; IMPORTANT: Set these variables in your private.el or custom-vars.el:
    ;; (setq org-gcal-client-id "your-client-id-from-google-console.apps.googleusercontent.com")
    ;; (setq org-gcal-client-secret "your-client-secret-from-google-console")
    ;; (setq org-gcal-file-alist '(("your-email@gmail.com" . "~/org/gcal.org")
    ;;                              ("another-calendar@gmail.com" . "~/org/work-gcal.org")))

    ;; Directory to store OAuth token and sync metadata
    (org-gcal-dir (expand-file-name ".org-gcal/" user-emacs-directory))

    ;; Token storage - use plain text file (no .gpg extension) to avoid encryption
    ;; The token file will have restricted file permissions (600) for security
    (org-gcal-token-file (expand-file-name ".org-gcal/token" user-emacs-directory))

    ;; Automatically fetch events when opening org-agenda
    (org-gcal-auto-archive nil)

    ;; Notify on sync
    (org-gcal-notify-p t)

    ;; Update events if they already exist (bidirectional sync)
    (org-gcal-update-cancelled-events-with-todo t)

    :init
    ;; CRITICAL: Disable plstore encryption BEFORE org-gcal loads
    ;; This must be in :init, not :config
    (setq plstore-cache-passphrase-for-symmetric-encryption t)
    (setq plstore-encrypt-to nil)

    ;; Ensure EPG context doesn't prompt for passphrase
    (setq epg-pinentry-mode 'loopback)

    ;; Auto-provide a passphrase if encryption can't be disabled
    ;; This prevents repeated prompts
    (defvar my/org-gcal-passphrase "emacs-gcal-token")
    (defun my/org-gcal-passphrase-callback (context key-id handback)
      "Automatically provide passphrase for org-gcal token encryption."
      my/org-gcal-passphrase)

    ;; Override EPG passphrase callback
    (setq epg-passphrase-callback-function #'my/org-gcal-passphrase-callback)

    :config
    ;; Additional workaround: advice plstore to disable encryption
    (when (fboundp 'plstore-open)
      (advice-add 'plstore-open :around
                  (lambda (orig-fun file)
                    (let ((plstore-encrypt-to nil))
                      (funcall orig-fun file)))))

    ;; Add org-gcal files to org-agenda-files if configured
    (when (and (boundp 'org-gcal-file-alist) org-gcal-file-alist)
      (dolist (calendar org-gcal-file-alist)
        (let ((gcal-file (cdr calendar)))
          ;; Create the file if it doesn't exist
          (unless (file-exists-p gcal-file)
            (make-directory (file-name-directory gcal-file) t)
            (write-region "" nil gcal-file))
          ;; Add to org-agenda-files if not already there
          (when (and (boundp 'org-agenda-files)
                     (not (member gcal-file org-agenda-files)))
            (add-to-list 'org-agenda-files gcal-file)))))

    :bind
    (("C-c g p" . org-gcal-post-at-point)
     ("C-c g d" . org-gcal-delete-at-point)
     ("C-c g r" . org-gcal-refresh-token)))
#+end_src

* Org Remote Images

Display remote HTTP/HTTPS images inline in org buffers with automatic caching.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-remoteimg.el
  ;;; org-remoteimg.el --- Display remote inline images in org-mode -*- lexical-binding: t -*-

  ;; Copyright (C) 2023 Dean Gao - MIT License
  ;; Author: Dean Gao <gao.dean@hotmail.com>
  ;; Description: Inline display of remote images in org-mode
  ;; Homepage: https://github.com/gaoDean/org-imgtog
  ;; Package-Requires: ((emacs "25.1"))

  ;; Permission is hereby granted, free of charge, to any person obtaining a copy
  ;; of this software and associated documentation files (the "Software"), to deal
  ;; in the Software without restriction, including without limitation the rights
  ;; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  ;; copies of the Software, and to permit persons to whom the Software is
  ;; furnished to do so, subject to the following conditions:
  ;;
  ;; The above copyright notice and this permission notice shall be included in all
  ;; copies or substantial portions of the Software.
  ;;
  ;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  ;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  ;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  ;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  ;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  ;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  ;; SOFTWARE.

  ;;; Commentary:

  ;; This package displays remote images inline in org-mode with automatic caching.
  ;; This means you can do \[\[https://my-file.png\]\], and have it display inline.
  ;; The next time you visit the file or fetch the image, it will be instantly
  ;; fetched from the cache.

  ;;; Code:

  (require 'org)
  (require 'org-element)
  (require 'url)
  (require 'url-cache)

  (unless (fboundp 'image-supported-file-p)
    ;; `image-supported-file-p' isn't available before Emacs 28
    ;; Add alias to not break Emacs <28.
    (defalias 'image-type-from-file-name 'image-supported-file-p))

  ;; Compatibility definitions for Org-mode < 9.8
  ;; In Org < 9.8, the variable is called org-inline-image-overlays
  ;; In Org >= 9.8, it was renamed to org-link-preview-overlays
  (unless (boundp 'org-link-preview-overlays)
    (defvaralias 'org-link-preview-overlays 'org-inline-image-overlays
      "Compatibility alias for org-inline-image-overlays in Org < 9.8."))

  (defun org-image-update-overlay (file link &optional data-p refresh)
    "Create image overlay for FILE associtated with org-element LINK.
  If DATA-P is non-nil FILE is not a file name but a string with the image data.
  If REFRESH is non-nil don't download the file but refresh the image.
  See also `create-image'.
  This function is almost a duplicate of a part of `org-display-inline-images'."
    (when (or data-p (file-exists-p file))
      (let ((width
             ;; Apply `org-image-actual-width' specifications.
             (cond
              ((eq org-image-actual-width t) nil)
              ((listp org-image-actual-width)
               (or
                ;; First try to find a width among
                ;; attributes associated to the paragraph
                ;; containing link.
                (let ((paragraph
                       (let ((e link))
                         (while (and (setq e (org-element-property
                                              :parent e))
                                     (not (eq (org-element-type e)
                                              'paragraph))))
                         e)))
                  (when paragraph
                    (save-excursion
                      (goto-char (org-element-property :begin paragraph))
                      (when
                          (re-search-forward
                           "^[ \t]*#\\+attr_.*?: +.*?:width +\\(\\S-+\\)"
                           (org-element-property
                            :post-affiliated paragraph)
                           t)
                        (string-to-number (match-string 1))))))
                ;; Otherwise, fall-back to provided number.
                (car org-image-actual-width)))
              ((numberp org-image-actual-width)
               org-image-actual-width)))
            (old (get-char-property-and-overlay
                  (org-element-property :begin link)
                  'org-image-overlay)))
        (if (and (car-safe old) refresh)
            (image-flush (overlay-get (cdr old) 'display))
          (let ((image (create-image file
                                     (and (image-type-available-p 'imagemagick)
                                          width
                                          'imagemagick)
                                     data-p
                                     :width width)))
            (when image
              (let* ((link
                      ;; If inline image is the description
                      ;; of another link, be sure to
                      ;; consider the latter as the one to
                      ;; apply the overlay on.
                      (let ((parent
                             (org-element-property :parent link)))
                        (if (eq (org-element-type parent) 'link)
                            parent
                          link)))
                     (ov (make-overlay
                          (org-element-property :begin link)
                          (progn
                            (goto-char
                             (org-element-property :end link))
                            (skip-chars-backward " \t")
                            (point)))))
                (overlay-put ov 'display image)
                (overlay-put ov 'face 'default)
                (overlay-put ov 'org-image-overlay t)
                (overlay-put
                 ov 'modification-hooks
                 (list 'org-display-inline-remove-overlay))
                (push ov org-link-preview-overlays)
                ov)))))))

  (defun org-display-user-inline-images (&optional _include-linked _refresh beg end)
    "Like `org-display-inline-images' but for image data links.
  _INCLUDE-LINKED and _REFRESH are ignored.
  Restrict to region between BEG and END if both are non-nil.
  Image data links have a :image-data-fun parameter.
  \(See `org-link-set-parameters'.)
  The value of the :image-data-fun parameter is a function
  taking the PROTOCOL, the LINK, and the DESCRIPTION as arguments.
  If that function returns nil the link is not interpreted as image.
  Otherwise the return value is the image data string to be displayed.

  Note that only bracket links are allowed as image data links
  with one of the formats
   [[PROTOCOL:LINK]]
  or
   [[PROTOCOL:LINK][DESCRIPTION]]
  are recognized.
  Full credit goes to org-yt by Tobias Zawada for this function."
    (interactive)
    (when (and (called-interactively-p 'any)
               (use-region-p))
      (setq beg (region-beginning)
            end (region-end)))
    (when (display-graphic-p)
      (org-with-wide-buffer
       (goto-char (or beg (point-min)))
       (when-let* ((image-data-link-parameters
		 (cl-loop for link-par-entry in org-link-parameters
			  with fun
			  when (setq fun (plist-get (cdr link-par-entry) :image-data-fun))
			  collect (cons (car link-par-entry) fun)))
		(image-data-link-re (regexp-opt (mapcar 'car image-data-link-parameters)))
		(re (format "\\[\\[\\(%s\\):\\([^]]+\\)\\]\\(?:\\[\\([^]]+\\)\\]\\)?\\]"
			    image-data-link-re)))
         (while (re-search-forward re end t)
           (let* ((protocol (match-string-no-properties 1))
		(link (match-string-no-properties 2))
		(description (match-string-no-properties 3))
		(image-data-link (assoc-string protocol image-data-link-parameters))
		(el (save-excursion (goto-char (match-beginning 1)) (org-element-context)))
		image-data)
             (when el
               (setq image-data
                     (or (let ((old (get-char-property-and-overlay
                                     (org-element-property :begin el)
                                     'org-image-overlay)))
                           (and old
                                (car-safe old)
                                (overlay-get (cdr old) 'display)))
		       (funcall (cdr image-data-link) protocol link description)))
               (when image-data
                 (let ((ol (org-image-update-overlay image-data el t t)))
                   (when (and ol description)
                     (overlay-put ol 'after-string description)))))))))))

  (defun org-remoteimg--fetch-image (protocol link _description)
    "Synchronously retrieve image from cache or web."
    (when (and (image-supported-file-p link)
               (not (eq org-display-remote-inline-images 'skip)))
      (let* ((cache (eq org-display-remote-inline-images 'cache))
             (url-automatic-caching (if cache
                                        t
                                      url-automatic-caching))
             (url (concat protocol ":" link))
             (silent-output (file-exists-p (url-cache-create-filename url))))
        (if-let* ((buf (url-retrieve-synchronously url
                                                     silent-output
                                                     nil
                                                     30)))
                (with-current-buffer buf
                  (goto-char (point-min))
                  (re-search-forward "\r?\n\r?\n" nil t)
                  (buffer-substring-no-properties (point) (point-max)))
              (error "Download of image \"%s\" failed" link)
              nil))))

  (defun org-link-preview-http (ov _path link)
    "Generate preview OV for LINK in PATH."
    (when-let* ((raw-link (org-element-property :raw-link link))
                (image-type (image-supported-file-p raw-link))
                ;; cache?
                (image-buffer (org-remoteimg--fetch-image nil raw-link nil)))
          (overlay-put ov 'display (create-image image-buffer
                                        ;; scale?
                                     ;; (and (image-type-available-p 'imagemagick)
                                     ;;      width
                                     ;;      'imagemagick)
                                                               ;; :width width
                                                               image-type
                                                               t))
          t))

  (if (fboundp 'org-display-inline-images)
      (progn
        (advice-add #'org-display-inline-images :after #'org-display-user-inline-images)
        (org-link-set-parameters "http"  :image-data-fun #'org-remoteimg--fetch-image)
        (org-link-set-parameters "https" :image-data-fun #'org-remoteimg--fetch-image))
    (org-link-set-parameters "http" :preview #'org-link-preview-http)
    (org-link-set-parameters "https" :preview #'org-link-preview-http))

  (provide 'org-remoteimg)

  ;;; org-remoteimg.el ends here

#+end_src

* Org-Roam Configuration

Org-roam is a powerful Zettelkasten-style note-taking system built on top of Org-mode. It enables networked thought through bidirectional linking and provides tools for knowledge management inspired by Roam Research.

** Core Setup

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam
    :after org
    :demand t
    :custom
    ;; Directory where all your notes will be stored
    (org-roam-directory (file-truename "~/org-roam/"))

    ;; Better database location (avoid cluttering org-roam directory)
    (org-roam-db-location (expand-file-name "org-roam.db" user-emacs-directory))

    ;; Enable completion everywhere (for inserting links)
    (org-roam-completion-everywhere t)

    ;; Configure how nodes are displayed in completion
    (org-roam-node-display-template
     (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))

    :bind
    (("C-c n l" . org-roam-buffer-toggle)         ;; Show backlinks sidebar
     ("C-c n f" . org-roam-node-find)             ;; Find or create a note
     ("C-c n i" . org-roam-node-insert)           ;; Insert a link to a note
     ("C-c n c" . org-roam-capture)               ;; Quick capture
     ("C-c n j" . org-roam-dailies-capture-today) ;; Daily note
     ("C-c n g" . org-roam-graph)                 ;; Visualize the graph
     :map org-mode-map
     ("C-M-i"   . completion-at-point))           ;; Complete link at point

    :config
    ;; Initialize org-roam database and sync on startup
    (org-roam-db-autosync-mode 1)

    ;; Ensure org-roam directory exists
    (unless (file-directory-p org-roam-directory)
      (make-directory org-roam-directory t)))
#+end_src

** Capture Templates

Define templates for different types of notes. This follows the best practice of having different note types (fleeting, permanent, literature, etc.).

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam
    :custom
    ;; Capture templates for different note types
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                           "#+title: ${title}\n#+date: %U\n#+filetags: \n\n")
        :unnarrowed t)

       ("p" "permanent" plain
        "* Source\n\n%?\n\n* Content\n\n\n* Links\n"
        :target (file+head "permanent/%<%Y%m%d%H%M%S>-${slug}.org"
                           "#+title: ${title}\n#+date: %U\n#+filetags: :permanent:\n\n")
        :unnarrowed t)

       ("l" "literature" plain
        "* Source\n\nAuthor: %^{Author}\nTitle: ${title}\nYear: %^{Year}\n\n%?\n\n* Summary\n\n\n* Key Points\n\n\n* Quotes\n\n\n* Related\n"
        :target (file+head "literature/%<%Y%m%d%H%M%S>-${slug}.org"
                           "#+title: ${title}\n#+date: %U\n#+filetags: :literature:\n\n")
        :unnarrowed t)

       ("c" "concept" plain
        "* Definition\n\n%?\n\n* Examples\n\n\n* Related Concepts\n"
        :target (file+head "concepts/%<%Y%m%d%H%M%S>-${slug}.org"
                           "#+title: ${title}\n#+date: %U\n#+filetags: :concept:\n\n")
        :unnarrowed t)

       ("r" "reference" plain
        "* %?\n"
        :target (file+head "reference/%<%Y%m%d%H%M%S>-${slug}.org"
                           "#+title: ${title}\n#+date: %U\n#+filetags: :reference:\n\n")
        :unnarrowed t))))
#+end_src

** Daily Notes Configuration

Daily notes are essential for journaling and capturing fleeting thoughts. This configuration follows best practices for daily note organization.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam
    :custom
    ;; Store daily notes in a dedicated subdirectory
    (org-roam-dailies-directory "daily/")

    ;; Capture templates for daily notes
    (org-roam-dailies-capture-templates
     '(("d" "default" entry
        "* %<%H:%M> %?"
        :target (file+head "%<%Y-%m-%d>.org"
                           "#+title: %<%Y-%m-%d (%A)>\n#+filetags: :daily:\n\n"))

       ("m" "meeting" entry
        "* %<%H:%M> Meeting: %^{Meeting Title}\n\n** Attendees\n%?\n\n** Notes\n\n\n** Action Items\n"
        :target (file+head "%<%Y-%m-%d>.org"
                           "#+title: %<%Y-%m-%d (%A)>\n#+filetags: :daily:\n\n"))

       ("j" "journal" entry
        "* %<%H:%M> Journal\n\n%?"
        :target (file+head "%<%Y-%m-%d>.org"
                           "#+title: %<%Y-%m-%d (%A)>\n#+filetags: :daily:journal:\n\n"))

       ("t" "task" entry
        "* TODO %?\n  SCHEDULED: %t\n"
        :target (file+head "%<%Y-%m-%d>.org"
                           "#+title: %<%Y-%m-%d (%A)>\n#+filetags: :daily:\n\n"))))

    :bind
    (("C-c n t" . org-roam-dailies-goto-today)
     ("C-c n y" . org-roam-dailies-goto-yesterday)
     ("C-c n d" . org-roam-dailies-goto-date)
     ("C-c n n" . org-roam-dailies-goto-next-note)
     ("C-c n p" . org-roam-dailies-goto-previous-note)))
#+end_src

** Enhanced Node Display

Customize how nodes appear in completion and searches for better usability.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam
    :config
    ;; Custom function to display nodes with more context
    (setq org-roam-node-display-template
          (concat "${type:15} ${title:*} " (propertize "${tags:20}" 'face 'org-tag)))

    ;; Add custom properties to node display
    (cl-defmethod org-roam-node-type ((node org-roam-node))
      "Return the TYPE of NODE based on tags or directory."
      (let ((tags (org-roam-node-tags node))
            (file (org-roam-node-file node)))
        (cond
         ((member "permanent" tags) "📝 Permanent")
         ((member "literature" tags) "📚 Literature")
         ((member "concept" tags) "💡 Concept")
         ((member "reference" tags) "📖 Reference")
         ((member "daily" tags) "📅 Daily")
         ((string-match-p "/daily/" file) "📅 Daily")
         ((string-match-p "/literature/" file) "📚 Literature")
         ((string-match-p "/permanent/" file) "📝 Permanent")
         ((string-match-p "/concepts/" file) "💡 Concept")
         (t "📄 Note")))))
#+end_src

** Graph Visualization

Configure org-roam's graph visualization for better insights into your knowledge network.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam
    :custom
    ;; Graphviz executable for generating graphs
    (org-roam-graph-executable (executable-find "dot"))

    ;; Exclude certain tags from the graph for cleaner visualization
    (org-roam-graph-exclude-matcher '("daily" "fleeting"))

    ;; Use specific program for graph generation
    (org-roam-graph-viewer (executable-find "open"))  ;; macOS
    ;; For Linux: (org-roam-graph-viewer "xdg-open")
    ;; For Windows: (org-roam-graph-viewer "start")

    ;; Additional graph settings
    (org-roam-graph-extra-config
     '(("overlap" . "false")
       ("splines" . "true")
       ("rankdir" . "LR"))))  ;; Left to Right layout
#+end_src

** UI Enhancement with org-roam-ui

Optional web-based graph visualization interface (requires separate package).

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam-ui
    :after org-roam
    :custom
    (org-roam-ui-sync-theme t)              ;; Sync with Emacs theme
    (org-roam-ui-follow t)                  ;; Follow current note in UI
    (org-roam-ui-update-on-save t)          ;; Update graph on save
    (org-roam-ui-open-on-start t)           ;; Open browser when activated
    (org-roam-ui-browser-function #'browse-url-default-browser)  ;; Use default browser
    :bind
    ("C-c n u" . org-roam-ui-mode))
#+end_src

** Performance Optimizations

Best practices for maintaining good performance with large note collections.

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf.el
  (use-package org-roam
    :custom
    ;; Increase cache size for better performance
    (org-roam-db-gc-threshold most-positive-fixnum)

    ;; Update database asynchronously
    (org-roam-db-update-method 'immediate)

    :config
    ;; Auto-save database periodically
    (run-with-idle-timer 300 t #'org-roam-db-sync))

  ;; Helper function for safe note deletion
  (defun fu/org-roam-node-delete (&optional node)
    "Delete an org-roam NODE after showing backlinks warning.
If NODE is not provided, prompt to select a note from minibuffer.
If called from within a note, can use current note."
    (interactive)
    (let* ((node (or node
                     (if (derived-mode-p 'org-mode)
                         ;; Try current node first, fall back to selection
                         (or (org-roam-node-at-point)
                             (org-roam-node-read))
                       ;; Not in org-mode, always prompt
                       (org-roam-node-read))))
           (file (org-roam-node-file node))
           (title (org-roam-node-title node))
           (backlinks (org-roam-backlinks-get node))
           (buffer (find-buffer-visiting file)))
      (if backlinks
          (progn
            ;; Open the file if not already open
            (unless buffer
              (find-file file))
            (org-roam-buffer-toggle)
            (message "WARNING: %d notes link to '%s'! Check backlinks first."
                     (length backlinks) title))
        (when (yes-or-no-p (format "Delete '%s'? " title))
          (when buffer (kill-buffer buffer))
          (delete-file file)
          (org-roam-db-sync)
          (message "Note '%s' deleted and database synced." title)))))

  (provide 'org-conf)
  ;;; org-conf.el ends here
#+end_src

** Best Practices Summary

Key principles to follow when using org-roam:

1. *Atomic Notes*: One idea per note - keeps notes focused and linkable
2. *Consistent Tagging*: Use tags systematically (e.g., =:permanent:=, =:literature:=, =:concept:=)
3. *Regular Capturing*: Use daily notes to capture fleeting thoughts immediately
4. *Link Liberally*: Create connections between notes to build your knowledge graph
5. *Regular Reviews*: Periodically review and refactor notes to strengthen connections
6. *Structured Templates*: Use capture templates to maintain consistency
7. *Hierarchical Organization*: Use subdirectories (daily/, literature/, etc.) for better organization
8. *Database Maintenance*: Let org-roam-db-autosync-mode handle synchronization automatically
9. *Safe Deletion*: Always check backlinks before deleting notes to avoid orphaned links

** Common Workflows

*** Creating a New Note
1. =C-c n f= (org-roam-node-find)
2. Type the note title
3. Select template (or use default)
4. Write your note with =[[links]]= to other notes

*** Linking Notes
1. =C-c n i= (org-roam-node-insert) while writing
2. Search for existing note or create new one
3. Link is created bidirectionally

*** Daily Journaling
1. =C-c n j= (org-roam-dailies-capture-today)
2. Select template (journal, meeting, task, etc.)
3. Write entry - automatically timestamped

*** Reviewing Connections
1. =C-c n l= (org-roam-buffer-toggle) to see backlinks
2. =C-c n g= (org-roam-graph) for visual exploration
3. =C-c n u= (org-roam-ui-mode) for interactive web interface

*** Deleting Notes Safely

*Method 1: Delete from anywhere (recommended)*
1. =M-x fu/org-roam-node-delete= from any buffer
2. Select the note to delete from minibuffer (with completion)
3. If backlinks exist, the note opens and backlinks sidebar shows warning
4. Check each linking note and update/remove links
5. Run the command again to confirm deletion
6. Database automatically syncs after deletion

*Method 2: Delete current note*
1. Open the note you want to delete
2. =M-x fu/org-roam-node-delete= (automatically uses current note)
3. Follow steps 3-6 from Method 1

*Alternative manual method:*
1. =C-c n l= to check backlinks first
2. Update all linking notes
3. Delete the file normally
4. =M-x org-roam-db-sync= to clean up the database

* Remote Access Setup

This section covers how to access org-roam from anywhere using cloud servers (AWS EC2, VPS, etc.) instead of Notion or Obsidian.

** Overview of Remote Access Approaches

| Approach        | Pros                            | Cons             | Best For                  |
|-----------------+---------------------------------+------------------+---------------------------|
| SSH + Mosh      | Low latency, no sync conflicts  | Requires network | Primary remote workflow   |
| org-roam-ui Web | Mobile-friendly, visual         | Read-only        | Browsing on mobile        |
| Git Sync        | Offline access, version control | Manual conflicts | Multiple devices          |
| TRAMP           | Use local Emacs                 | Some lag         | Occasional remote editing |

** AWS EC2 / VPS Setup Guide

*** Initial Server Setup

*Prerequisites:*
- AWS account or any VPS provider (DigitalOcean, Linode, etc.)
- SSH key pair configured

*Launch Instance:*
#+begin_src shell
# Recommended specs:
# - t2.micro or t3.micro (AWS free tier)
# - Ubuntu 24.04 LTS
# - 1GB RAM minimum, 20GB disk
# - Security group: SSH (22), Mosh (60000-61000 UDP), optional HTTP (8080)
#+end_src

*Install dependencies on server:*
#+begin_src shell
sudo apt update && sudo apt install -y \
  emacs-nox \
  tmux \
  mosh \
  sqlite3 \
  ripgrep \
  git \
  build-essential
#+end_src

*** Transfer Org-Roam Files

*Option 1: Git (recommended)*
#+begin_src shell
# On local machine - push org-roam to Git
cd ~/org-roam
git init
echo "org-roam.db" >> .gitignore  # IMPORTANT: Never sync database!
git add .
git commit -m "Initial org-roam commit"
git remote add origin <your-repo-url>
git push -u origin main

# On EC2 server - clone repository
git clone <your-repo-url> ~/org-roam
#+end_src

*Option 2: SCP (one-time copy)*
#+begin_src shell
# Copy from local to server (excludes database)
rsync -avz --exclude='org-roam.db' ~/org-roam/ user@ec2-ip:~/org-roam/
#+end_src

*** Configure Emacs on Server

*Transfer your Emacs configuration:*
#+begin_src shell
# Option 1: If using this repository
cd ~/Projects/mandoo180.github.io
git push
# Then on server:
git clone <this-repo-url>
cd mandoo180.github.io
./tangle.sh

# Option 2: Copy specific config
scp -r ~/.emacs.d/elisp/settings/org-conf.el user@ec2-ip:~/.emacs.d/elisp/settings/
#+end_src

*Start Emacs daemon:*
#+begin_src shell
# On server
emacs --daemon
#+end_src

*** Systemd Service for Auto-Start

Create a systemd service to start Emacs daemon automatically on boot.

#+begin_src conf :tangle no
# ~/.config/systemd/user/emacs.service
[Unit]
Description=Emacs text editor daemon
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

[Service]
Type=notify
ExecStart=/usr/bin/emacs --fg-daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Environment=SSH_AUTH_SOCK=%t/keyring/ssh
Restart=on-failure

[Install]
WantedBy=default.target
#+end_src

*Enable the service:*
#+begin_src shell
# On server
mkdir -p ~/.config/systemd/user
# Create the service file above, then:
systemctl --user enable emacs.service
systemctl --user start emacs.service
systemctl --user status emacs.service
#+end_src

** Fast SSH Access with Mosh

Mosh (Mobile Shell) provides near-zero latency for remote Emacs usage.

*** Install Mosh

*On your local machine (macOS):*
#+begin_src shell
brew install mosh
#+end_src

*On server:*
#+begin_src shell
sudo apt install mosh
#+end_src

*** Configure Firewall

*AWS Security Group:*
- Add inbound rule: UDP ports 60000-61000 from your IP

*UFW (on server):*
#+begin_src shell
sudo ufw allow 60000:61000/udp
#+end_src

*** Connect with Mosh

#+begin_src shell
# Instead of: ssh user@ec2-ip
mosh user@ec2-ip

# Inside mosh session
tmux attach || tmux new
emacsclient -nw

# Your org-roam is now accessible!
C-c n f  # Find notes
C-c n u  # Open web UI
#+end_src

*Benefits over SSH:*
- Typing appears instantly (local echo)
- Survives network changes (WiFi → cellular)
- Automatic reconnection after laptop sleep
- Works on spotty connections

** org-roam-ui for Mobile Web Access

Access your knowledge graph from any device with a web browser.

*** Local Access (SSH Tunnel)

Most secure method - UI only accessible through SSH tunnel.

*In terminal:*
#+begin_src shell
# Create SSH tunnel
ssh -L 35901:localhost:35901 user@ec2-ip

# Keep this terminal open, then in Emacs on server:
M-x org-roam-ui-mode
#+end_src

*Access on any device:*
- Open browser to =http://localhost:35901=
- Works on desktop, phone, tablet
- No public exposure

*** Remote Access (Bind to Public IP)

For direct access without SSH tunnel (less secure).

#+begin_src emacs-lisp :tangle ~/.emacs.d/elisp/settings/org-conf-remote.el
  ;;; org-conf-remote.el --- Remote access configuration  -*- lexical-binding: t; -*-
  ;;; Commentary:
  ;; Configuration for accessing org-roam-ui from remote devices
  ;;; Code:

  ;; Only enable this on your remote server, not local machine
  (when (getenv "ORG_ROAM_REMOTE")
    (use-package org-roam-ui
      :custom
      ;; Bind to all interfaces for remote access
      (org-roam-ui-host "0.0.0.0")  ;; WARNING: Exposes to internet
      (org-roam-ui-port 8080)       ;; Or use reverse proxy

      ;; Optional: Add basic auth via reverse proxy (nginx/caddy)
      ;; See nginx configuration example below
      ))

  (provide 'org-conf-remote)
  ;;; org-conf-remote.el ends here
#+end_src

*Set environment variable on server:*
#+begin_src shell
# Add to ~/.bashrc or ~/.zshrc
export ORG_ROAM_REMOTE=1
#+end_src

*Secure with reverse proxy (Nginx example):*
#+begin_src nginx :tangle no
# /etc/nginx/sites-available/org-roam
server {
    listen 80;
    server_name roam.yourdomain.com;

    # Basic authentication
    auth_basic "Org-Roam Access";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://localhost:35901;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
#+end_src

** iOS Quick Capture Setup

For capturing notes on iPhone/iPad while org-roam runs on server.

*** Option 1: Working Copy + Git Sync

*Setup:*
1. Install [[https://workingcopy.app/][Working Copy]] app (iOS Git client)
2. Clone your org-roam repository
3. Install [[https://www.beorgapp.com/][beorg]] or [[https://plainorg.com/][Plain Org]] for editing
4. Configure beorg to use Working Copy directory

*Workflow:*
1. Create/edit notes in beorg
2. Switch to Working Copy
3. Commit and push changes
4. On server: =git pull= (or set up auto-pull)
5. =M-x org-roam-db-sync= in Emacs

*** Option 2: SSH Terminal App

*Install terminal app with mosh support:*
- [[https://blink.sh/][Blink Shell]] (iOS) - supports mosh
- [[https://termius.com/][Termius]] - user-friendly SSH client

*Connect to your server:*
#+begin_src shell
mosh user@ec2-ip
tmux attach
emacsclient -nw
# Full org-roam access on iPhone!
#+end_src

** Git Sync Workflow

For offline access and automatic synchronization.

*** Auto-Commit Script

#+begin_src shell :tangle no :shebang "#!/bin/bash"
# ~/bin/org-roam-sync.sh
# Automatically sync org-roam changes

cd ~/org-roam || exit

# Pull latest changes
git pull --rebase

# Add all changes
git add *.org

# Commit if there are changes
if ! git diff-index --quiet HEAD --; then
    git commit -m "Auto-sync: $(date '+%Y-%m-%d %H:%M')"
    git push
    echo "Changes synced at $(date)"
fi
#+end_src

*Set up cron job (run every 5 minutes):*
#+begin_src shell
crontab -e
# Add line:
*/5 * * * * ~/bin/org-roam-sync.sh >> ~/logs/org-sync.log 2>&1
#+end_src

*Sync database after pull:*
#+begin_src emacs-lisp :tangle no
;; Auto-sync database when files change
(defun fu/org-roam-auto-sync ()
  "Automatically sync org-roam database when files change."
  (when (and (buffer-file-name)
             (string-prefix-p (expand-file-name org-roam-directory)
                            (buffer-file-name)))
    (org-roam-db-sync)))

(add-hook 'after-save-hook #'fu/org-roam-auto-sync)
#+end_src

** Backup Strategy

*** Git as Backup

Your Git repository serves as automatic backup:
#+begin_src shell
# All changes are version controlled
git log --oneline  # See history
git show <commit>  # View specific changes
git checkout <commit> -- file.org  # Restore old version
#+end_src

*** S3 Backup (AWS)

For additional cloud backup:
#+begin_src shell
# Install AWS CLI
sudo apt install awscli

# Configure credentials
aws configure

# Backup script
aws s3 sync ~/org-roam/ s3://my-org-roam-backup/ \
    --exclude "*.db" \
    --exclude ".git/*"
#+end_src

** Daily Workflow Examples

*** Morning Routine (Desktop)
#+begin_src shell
# Connect to server
mosh user@ec2-ip

# Start/resume tmux session
tmux attach || tmux new

# Start Emacs
emacsclient -nw

# Check daily notes
C-c n t  # Today's note
C-c n l  # View backlinks
C-c n u  # Open graph on tablet
#+end_src

*** Quick Capture (Mobile - iOS)
1. Open Blink Shell on iPhone
2. =mosh user@server=
3. =C-c n j= for quick journal entry
4. Type note and save
5. Swipe away - session persists

*** Browsing on iPad
1. Safari → =http://localhost:35901= (if SSH tunnel running)
2. Or direct IP if configured with auth
3. Explore graph visually
4. Click nodes to read content

** Troubleshooting

*** Database Issues

*Symptom:* "Database version mismatch" error

*Solution:*
#+begin_src shell
# Delete database and regenerate
rm ~/.emacs.d/org-roam.db
# In Emacs:
M-x org-roam-db-sync
#+end_src

*** Mosh Won't Connect

*Check firewall:*
#+begin_src shell
# On server
sudo ufw status
sudo ufw allow 60000:61000/udp

# AWS Security Group
# Add UDP 60000-61000 inbound rule
#+end_src

*** Emacs Daemon Not Starting

*Check status:*
#+begin_src shell
systemctl --user status emacs.service
journalctl --user -u emacs.service -f
#+end_src

*Manual start:*
#+begin_src shell
emacs --daemon --debug-init
#+end_src

*** org-roam-ui Not Accessible

*Verify it's running:*
#+begin_src shell
# On server
netstat -tlnp | grep 35901
# or
lsof -i :35901
#+end_src

*Test locally first:*
#+begin_src shell
# SSH into server
curl http://localhost:35901
# Should return HTML
#+end_src

** Cost Estimation

*** AWS EC2 Free Tier
- t2.micro: Free for 12 months (750 hours/month)
- After free tier: ~$8/month
- Storage: 20GB free tier

*** Alternative VPS Providers
- DigitalOcean: $4/month (basic droplet)
- Linode: $5/month (Nanode 1GB)
- Hetzner: €3.79/month (CX11)

*** Total Monthly Cost
- Server: $0-8/month
- iOS apps: $0-15 (one-time for beorg)
- **Total: $0-10/month** vs Notion ($12/mo) or Obsidian Sync ($4/mo)

** Comparison to Notion/Obsidian

| Feature | Org-Roam (Remote) | Obsidian | Notion |
|---------|-------------------|----------|--------|
| Cost | $0-10/mo | $4/mo (sync) | $12/mo |
| Mobile apps | Terminal/web | Native | Native |
| Offline | Optional | Yes | Limited |
| Privacy | Full control | Full control | Cloud-based |
| Sync | Manual/Git | Auto | Auto |
| Learning curve | High | Medium | Low |

*Advantages of remote org-roam:*
- ✅ Single source of truth (no conflicts)
- ✅ Full Emacs power
- ✅ Plain text + version control
- ✅ Zero vendor lock-in
- ✅ Works on any device with SSH

*Disadvantages:*
- ❌ Requires technical setup
- ❌ No native mobile apps
- ❌ Needs network for full features

** References and Resources

- [[https://mosh.org/][Mosh (Mobile Shell)]]
- [[https://github.com/org-roam/org-roam-ui][org-roam-ui GitHub]]
- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html][Emacs Server Documentation]]
- [[https://blink.sh/][Blink Shell (iOS)]]
- [[https://www.beorgapp.com/][beorg (iOS Org-mode app)]]
- [[https://plainorg.com/][Plain Org (iOS)]]
